### PR TITLE
adds comparison with jsonaf

### PR DESCRIPTION
**Pull request by anuragsoni**

### CODE REVIEW

**Comment by anuragsoni** [comment]
this includes changes from #3 as well

**Comment by rgrinberg** [comment]
Is committing the entire lock dir the recommended practice for locking deps? I thought that just one file was necessary.

**Comment by anuragsoni** [comment]
I believe so. I see this in the `.gitignore` auto generated by esy

```
# Reset any possible .gitignore, we want all esy.lock to be un-ignored.
!*
```

**Comment by anuragsoni** [comment]
Also for anyone curious, these were the results on my laptop:
```
Estimated testing time 30s (3 benchmarks x 10s). Change using -quota SECS.
┌──────────────┬──────────┬────────────┬──────────┬──────────┬────────────┐
│ Name         │ Time/Run │    mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────────────┼──────────┼────────────┼──────────┼──────────┼────────────┤
│ ezjsonm read │   3.69ms │ 1_226.33kw │  65.67kw │  65.67kw │    100.00% │
│ yojson read  │   1.38ms │   157.35kw │  40.99kw │  23.96kw │     37.44% │
│ jsonaf read  │   2.89ms │   855.82kw │  75.58kw │  75.07kw │     78.38% │
└──────────────┴──────────┴────────────┴──────────┴──────────┴────────────┘

```

```
Estimated testing time 30s (3 benchmarks x 10s). Change using -quota SECS.
┌─────────────────────────┬────────────┬──────────┬──────────┬──────────┬────────────┐
│ Name                    │   Time/Run │  mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├─────────────────────────┼────────────┼──────────┼──────────┼──────────┼────────────┤
│ ezjsonm write to string │ 1_482.47us │ 348.58kw │ 113.51kw │  30.93kw │    100.00% │
│ yojson write to string  │   893.86us │  56.27kw │  87.90kw │   5.57kw │     60.30% │
│ Jsonaf write to string  │   666.91us │ 102.59kw │  26.09kw │   9.06kw │     44.99% │
└─────────────────────────┴────────────┴──────────┴──────────┴──────────┴────────────┘
```

**Pull request merged**
